# Generated by Django 4.2 on 2024-08-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=200)),
                ('publishedAt', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
